# Generated by Django 5.1.4 on 2024-12-31 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(800)])),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'fridge',
                'verbose_name_plural': 'fridges',
                'db_table': 'fridges',
                'ordering': ['brand', 'model'],
                'indexes': [models.Index(['date_created'], name='date_created_index'), models.Index(fields=['slug'], name='slug_index')],
            },
        ),
    ]
